#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "markdown-it-py>=3",
#   "mdit-py-plugins>=0.4",
#   "ruamel.yaml>=0.18",
#   "unidiff>=0.7",
#   "tenacity>=8",
# ]
# ///
"""
spec-align.py -- keeps a project's specs and its implementation in step, for l3io-pm.

Subcommands: build, check-pointers, sections, disposition, check-dispositions, adrs,
check-links, lease, sync-plan, propose, commit, reject, check-stale, migrate-adrs.

It never calls a model. Each spec-alignment point in l3io-execute runs one of these
first, and the result decides whether an agent is dispatched at all.

Global flags come before the subcommand: --project-root (required), --planning-root,
--impl-root, --state-root (default <impl-root>/state), --pm-status, --spec-paths JSON.

Exit codes: 0 ok; 1 a report-mode check found problems; 2 a gate refused, or bad input;
5 the spec-sync lease is held by another owner.

Design: docs/superpowers/specs/2026-09-11-spec-alignment-design.md in the package repo;
decisions: docs/adr/0004-agents-edit-architecture-specs.md, docs/adr/0005-one-adr-home.md.
"""
import argparse
import fnmatch
import glob
import hashlib
import json
import os
import re
import shlex
import subprocess
import sys
import tempfile
import time
from datetime import UTC

INDEX_FORMAT = 1
INDEX_REL = os.path.join("spec", "spec-index.md")
INDEX_MAX_LEVEL = 3
SUMMARY_CHARS = 100
SIZE_WARN_BYTES = 16384
HEADER_TITLE = "# Spec index — generated by spec-align.py; do not edit"
DIGEST_RE = re.compile(r"^# inputs-sha256: ([0-9a-f]{64})\b")
SPEC_PATHS_RE = re.compile(r"^# spec-paths: (.*)$")

# Spec kinds in precedence order: a name matching several kinds takes the first. The
# architecture, ux and prd patterns are copied verbatim from
# l3io-doctor/steps/clean-layout.md heuristic 5 -- check-docs check 13 compares them.
KINDS = (
    ("architecture", ("*architecture*", "*arch-spec*", "*system-design*", "*tech-design*")),
    ("ux", ("*ux-spec*", "*ux-design*", "*wireframe*", "*mockup*", "*ui-spec*")),
    ("prd", ("*requirements*", "*prd*", "*brief*", "*spec*")),
    ("epics", ("*epics*",)),
)
KIND_ORDER = {k: i for i, (k, _) in enumerate(KINDS)}


class SAError(Exception):
    """A refusal: `code` is the exit status; the message goes to stderr."""

    def __init__(self, code, msg):
        super().__init__(msg)
        self.code = code


class Ctx:
    """The paths every subcommand resolves against, from the global flags."""

    def __init__(self, a):
        self.project = os.path.abspath(a.project_root)
        self.planning = os.path.abspath(a.planning_root) if a.planning_root else None
        self.impl = os.path.abspath(a.impl_root) if a.impl_root else None
        self.state_root = (os.path.abspath(a.state_root) if a.state_root
                           else (os.path.join(self.impl, "state") if self.impl else None))
        self.pm_status = a.pm_status or None
        self.spec_paths_arg = None
        if a.spec_paths is not None:
            if not a.spec_paths.strip():
                value = []
            else:
                try:
                    value = json.loads(a.spec_paths)
                except ValueError as e:
                    raise SAError(2, f"--spec-paths is not JSON: {e}")
            if not isinstance(value, list) or not all(isinstance(x, str) for x in value):
                raise SAError(2, "--spec-paths must be a JSON list of strings")
            self.spec_paths_arg = value

    def need(self, *what):
        flags = {"impl": ("--impl-root", self.impl), "state": ("--state-root", self.state_root),
                 "pm": ("--pm-status", self.pm_status)}
        missing = [flags[w][0] for w in what if not flags[w][1]]
        if missing:
            raise SAError(2, f"this subcommand needs {', '.join(missing)}")

    def rel(self, p):
        return os.path.relpath(os.path.abspath(p), self.project).replace(os.sep, "/")

    def abs(self, p):
        return p if os.path.isabs(p) else os.path.join(self.project, p)

    def index_path(self):
        self.need("impl")
        return os.path.join(self.impl, INDEX_REL)


def _under(path, root):
    path, root = os.path.abspath(path), os.path.abspath(root)
    return path == root or path.startswith(root + os.sep)


def read_text(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def atomic_write(path, text):
    """Write via a sibling temp file + os.replace, so a reader never sees half a file."""
    d = os.path.dirname(os.path.abspath(path))
    os.makedirs(d, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".spec-align-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


# -- markdown ------------------------------------------------------------------------------ #

_MD = None


def md():
    """One parser for every read. Anchors are computed over every heading level, so duplicate
    suffixes (-1, -2) count the same headings GitHub does; the index lists H1-H3 only."""
    global _MD
    if _MD is None:
        try:
            from markdown_it import MarkdownIt
            from mdit_py_plugins.anchors import anchors_plugin
        except ImportError as exc:
            # This script's dependencies come from its PEP-723 header, which only `uv run`
            # reads. Reached under a bare interpreter, the lazy import dies with a traceback
            # naming a package nobody asked for -- so say what is actually wrong instead.
            raise SAError(2, f"spec-align.py needs its PEP-723 dependencies ({exc.name}). "
                             f"Run it under uv, not a bare interpreter:\n"
                             f"  uv run {os.path.basename(__file__)} <subcommand> ...") from exc
        _MD = MarkdownIt("commonmark").enable("table").use(anchors_plugin,
                                                           min_level=1, max_level=6)
    return _MD


class Section:
    __slots__ = ("anchor", "end", "level", "start", "summary", "title")

    def __init__(self, level, title, anchor, start, end, summary):
        self.level, self.title, self.anchor = level, title, anchor
        self.start, self.end, self.summary = start, end, summary


def first_sentence(text):
    s = " ".join(text.split())
    m = re.match(r"(.+?[.!?])(?:\s|$)", s)
    if m:
        s = m.group(1)
    return s if len(s) <= SUMMARY_CHARS else s[:SUMMARY_CHARS - 1].rstrip() + "…"


def parse_sections(text):
    """Every heading as a Section. A section runs from its heading line to the line before
    the next heading of the same or a higher level (1-based, inclusive)."""
    tokens = md().parse(text)
    nlines = len(text.splitlines())
    heads = [(i, int(t.tag[1:]), t.attrs.get("id"), t.map[0], tokens[i + 1].content.strip())
             for i, t in enumerate(tokens) if t.type == "heading_open"]
    out = []
    for n, (i, level, anchor, line0, title) in enumerate(heads):
        end = nlines
        for _, level2, _, line2, _ in heads[n + 1:]:
            if level2 <= level:
                end = line2
                break
        stop = heads[n + 1][0] if n + 1 < len(heads) else len(tokens)
        summary = ""
        for j in range(i + 3, stop):
            if (tokens[j].type == "paragraph_open" and j + 1 < stop
                    and tokens[j + 1].type == "inline"):
                summary = first_sentence(tokens[j + 1].content)
                break
        out.append(Section(level, title, anchor, line0 + 1, max(end, line0 + 1), summary))
    return out


# -- discovery and the catalog -------------------------------------------------------------- #

def kind_of(name):
    low = name.lower()
    for kind, patterns in KINDS:
        if any(fnmatch.fnmatchcase(low, p) for p in patterns):
            return kind
    return None


def _kind_for_path(p):
    """A file takes its own name's kind, else its directory's (a sharded doc's section)."""
    return kind_of(os.path.basename(p)) or kind_of(os.path.basename(os.path.dirname(p)))


def recorded_spec_paths(ctx):
    """The spec-paths list the current index was built with, or None."""
    if not ctx.impl:
        return None
    p = os.path.join(ctx.impl, INDEX_REL)
    if not os.path.isfile(p):
        return None
    with open(p, encoding="utf-8") as fh:
        for n, line in enumerate(fh):
            if n > 4:
                break
            m = SPEC_PATHS_RE.match(line.rstrip("\n"))
            if m:
                try:
                    value = json.loads(m.group(1))
                except ValueError:
                    return None
                return value if isinstance(value, list) else None
    return None


def effective_spec_paths(ctx):
    """--spec-paths when given; else the list the index records (so doctor, which cannot read
    pm-execute's customize.toml, checks the same spec set); else [] (discover)."""
    if ctx.spec_paths_arg is not None:
        return list(ctx.spec_paths_arg)
    rec = recorded_spec_paths(ctx)
    return rec if rec is not None else []


def discover(ctx):
    """[(project-relative path, kind)], sorted. spec_paths replaces discovery entirely."""
    found = {}
    skip = os.path.join(ctx.impl, "spec") if ctx.impl else None      # never index the index
    patterns = effective_spec_paths(ctx)
    if patterns:
        for pat in patterns:
            for hit in glob.glob(os.path.join(ctx.project, pat), recursive=True):
                if os.path.isfile(hit) and hit.endswith(".md") and not (skip and _under(hit, skip)):
                    found[ctx.rel(hit)] = _kind_for_path(hit) or "other"
    elif ctx.planning and os.path.isdir(ctx.planning):
        for dirpath, dirnames, filenames in os.walk(ctx.planning):
            if skip and _under(dirpath, skip):
                dirnames[:] = []
                continue
            keep = []
            for d in sorted(dirnames):
                full = os.path.join(dirpath, d)
                kind = kind_of(d)
                if skip and _under(full, skip):
                    continue
                if kind and os.path.isfile(os.path.join(full, "index.md")):
                    for sub_dir, _, sub_files in os.walk(full):
                        for f in sub_files:
                            if f.endswith(".md"):
                                found[ctx.rel(os.path.join(sub_dir, f))] = kind
                else:
                    keep.append(d)
            dirnames[:] = keep
            for f in filenames:
                if f.endswith(".md"):
                    kind = kind_of(f)
                    if kind:
                        found[ctx.rel(os.path.join(dirpath, f))] = kind
    return sorted(found.items())


def load_catalog(ctx):
    """{rel: {"kind", "sections", "anchors", "error", "sha"}} for every discovered spec."""
    cat = {}
    for rel, kind in discover(ctx):
        e = {"kind": kind, "sections": [], "anchors": {}, "error": None, "sha": ""}
        try:
            with open(ctx.abs(rel), "rb") as fh:
                raw = fh.read()
        except OSError as exc:
            e["error"], e["sha"] = f"unreadable: {exc.strerror or exc}", "unreadable"
        else:
            e["sha"] = hashlib.sha256(raw).hexdigest()
            try:
                text = raw.decode("utf-8")
            except UnicodeDecodeError:
                e["error"] = "not UTF-8"
            else:
                e["sections"] = parse_sections(text)
                e["anchors"] = {s.anchor: s for s in e["sections"]}
        cat[rel] = e
    return cat


def inputs_hash(ctx, cat):
    h = hashlib.sha256()
    h.update(f"format={INDEX_FORMAT}\n"
             f"spec-paths={json.dumps(effective_spec_paths(ctx))}\n".encode())
    for rel in sorted(cat):
        h.update(f"{rel}\0{cat[rel]['sha']}\n".encode())
    return h.hexdigest()


def render_index(ctx, cat, digest):
    body, skipped, n_specs, n_sections = [], [], 0, 0
    for rel in sorted(cat, key=lambda r: (KIND_ORDER.get(cat[r]["kind"], 99), r)):
        e = cat[rel]
        if e["error"]:
            skipped.append(f"- skipped: {rel} ({e['error']})")
            continue
        n_specs += 1
        body.append(f"## {e['kind']} · {rel}")
        for s in e["sections"]:
            if s.level > INDEX_MAX_LEVEL:
                continue
            n_sections += 1
            summary = f": {s.summary}" if s.summary else ""
            body.append(f"- {rel}#{s.anchor} — {s.title}{summary} (L{s.start}–{s.end})")
    if skipped:
        body += ["## skipped", *skipped]
    if not cat:
        body.append("no spec docs found")
    text = "\n".join(body) + "\n"
    nbytes = len(text.encode("utf-8"))            # R12: the body below the header
    header = (f"{HEADER_TITLE}\n"
              f"# inputs-sha256: {digest}  ·  bytes: {nbytes:,}  ·  specs: {n_specs}  ·  "
              f"sections: {n_sections}\n"
              f"# spec-paths: {json.dumps(effective_spec_paths(ctx))}\n")
    return header + text, nbytes, n_specs, n_sections


def index_digest(path):
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as fh:
        for n, line in enumerate(fh):
            if n > 4:
                break
            m = DIGEST_RE.match(line)
            if m:
                return m.group(1)
    return None


def cmd_build(ctx, a):
    path = ctx.index_path()
    cat = load_catalog(ctx)
    digest = inputs_hash(ctx, cat)
    fresh = index_digest(path) == digest
    if a.check:
        if fresh:
            print(f"OK build --check: {ctx.rel(path)} is fresh")
            return 0
        print(f"STALE {ctx.rel(path)}: the specs changed since it was built "
              f"(or it does not exist) -- run build")
        return 1
    if a.if_stale and fresh:
        print(f"OK build: {ctx.rel(path)} is fresh; not rewritten")
        return 0
    text, nbytes, n_specs, n_sections = render_index(ctx, cat, digest)
    atomic_write(path, text)
    if nbytes > SIZE_WARN_BYTES:
        sys.stderr.write(f"WARN spec index is {nbytes:,} bytes (> {SIZE_WARN_BYTES:,}); every "
                         f"reviewer reads it -- consider trimming (spec §8)\n")
    print(f"OK build: wrote {ctx.rel(path)} ({n_specs} spec(s), {n_sections} section(s), "
          f"{nbytes:,} bytes)")
    return 0


# -- provenance pointers ---------------------------------------------------------------------- #

# The six technical-AC dimensions, in the order the enrichment prompt writes them
# (steps/sprint/step-02-story-prep.md §2). check-docs check 13 compares this tuple with the
# prompt's layout block; keep it a literal, one name per line.
DIMENSIONS = (
    "Interface contracts",
    "Error and edge case handling",
    "Observability requirements",
    "Security considerations",
    "Testability approach",
    "Existing-library check",
)
TAC_HEADING = "Technical acceptance criteria"
# The two business-AC dimensions, in the order the enrichment prompt writes them
# (steps/sprint/step-02-story-prep.md §2). check-docs check 13 compares this tuple with the
# prompt's layout block; keep it a literal, one name per line.
BUSINESS_DIMENSIONS = (
    "Outcome",
    "Non-goals",
)
BAC_HEADING = "Business acceptance criteria"
# Dimensions exempt from the `Spec:` requirement: a negative scope statement has no spec
# section to resolve against, and demanding `Spec: none — n/a` on every story is noise.
NO_POINTER_DIMENSIONS = frozenset({"Non-goals"})
SPEC_LINE_RE = re.compile(r"^\s*(?:[-*]\s+)?Spec:\s*(.*?)\s*$")
NONE_RE = re.compile(r"^none\s*(?:—|--|-)\s*(\S.*)$", re.IGNORECASE)
PTR_RE = re.compile(r"^([^\s#`]+\.md)#([^\s#`]+)$")
NA_RE = re.compile(r"^\s*N/A\s*(?:—|--|-)\s*\S")


def story_dimensions(text):
    """({section: h2 found}, {section: {casefolded dimension: (h3 line, [(lineno, line), ...])}})
    for the story's `## Business acceptance criteria` ("bac") and `## Technical acceptance
    criteria` ("tac") sections. Dimensions are kept per section, so one placed under the wrong
    h2 satisfies neither gate. Lines inside fenced or indented code are dropped."""
    tokens = md().parse(text)
    lines = text.splitlines()
    fenced = set()
    for t in tokens:
        if t.type in ("fence", "code_block") and t.map:
            fenced.update(range(t.map[0], t.map[1]))
    heads = [(t.map[0], int(t.tag[1:]), tokens[i + 1].content.strip())
             for i, t in enumerate(tokens) if t.type == "heading_open"]
    found, dims = {}, {"bac": {}, "tac": {}}
    for key, heading in (("bac", BAC_HEADING), ("tac", TAC_HEADING)):
        at = next((ln for ln, lvl, title in heads
                   if lvl == 2 and title.casefold() == heading.casefold()), None)
        found[key] = at is not None
        if at is None:
            continue
        end = next((ln for ln, lvl, _ in heads if ln > at and lvl <= 2), len(lines))
        h3 = [(ln, title) for ln, lvl, title in heads if at < ln < end and lvl == 3]
        for n, (ln, title) in enumerate(h3):
            stop = h3[n + 1][0] if n + 1 < len(h3) else end
            body = [(i + 1, lines[i]) for i in range(ln + 1, stop) if i not in fenced]
            dims[key][title.casefold()] = (ln + 1, body)
    return found, dims


def resolve_pointer(cat, value):
    """((path, anchor, Section, kind), None) or (None, why)."""
    m = PTR_RE.match(value.strip().strip("`"))
    if not m:
        return None, f"not a pointer: {value!r} (expected <path>#<anchor>)"
    path, anchor = m.groups()
    e = cat.get(path)
    if e is None:
        return None, f"{path} is not in the spec index"
    if e["error"]:
        return None, f"{path} is unreadable ({e['error']})"
    s = e["anchors"].get(anchor)
    if s is None:
        return None, f"{path} has no anchor #{anchor}"
    return (path, anchor, s, e["kind"]), None


def story_pointers(text):
    """[(lineno, dimension, value)] for every Spec: line under a known dimension."""
    _found, dims = story_dimensions(text)
    out = []
    for sect, names in (("tac", DIMENSIONS), ("bac", BUSINESS_DIMENSIONS)):
        for dim in names:
            for n, line in (dims[sect].get(dim.casefold()) or (0, []))[1]:
                m = SPEC_LINE_RE.match(line)
                if m:
                    out.append((n, dim, m.group(1)))
    return out


def _check_dimensions(cat, dims, names):
    """[(lineno, message)] for one section's dimension tuple."""
    errs = []
    for dim in names:
        d = dims.get(dim.casefold())
        if d is None:
            errs.append((0, f"{dim}: missing dimension (### {dim})"))
            continue
        h3_line, body = d
        content = [(n, line) for n, line in body if line.strip()]
        if not content:
            errs.append((h3_line, f"{dim}: empty"))
            continue
        if NA_RE.match(content[0][1]):
            continue
        if dim in NO_POINTER_DIMENSIONS:
            continue
        specs = [(n, SPEC_LINE_RE.match(line).group(1)) for n, line in content
                 if SPEC_LINE_RE.match(line)]
        if not specs:
            errs.append((h3_line, (f"{dim}: no Spec: line -- end it with `Spec: <path>#<anchor>` "
                                  f"or `Spec: none — <reason>`")))
            continue
        nones = [(n, v) for n, v in specs if v.lower().startswith("none")]
        if nones:
            if len(specs) > 1:
                errs.append((nones[0][0], f"{dim}: `Spec: none` must be the only Spec: line"))
            elif not NONE_RE.match(nones[0][1]):
                errs.append((nones[0][0], f"{dim}: `Spec: none` needs a reason after the dash"))
            continue
        for n, v in specs:
            hit, why = resolve_pointer(cat, v)
            if hit is None:
                errs.append((n, f"{dim}: {why}"))
    return errs


def check_story(cat, text):
    """(technical, business). technical is None when the story has no `## Technical acceptance
    criteria` section (pre-provenance). business is None when it has no `## Business acceptance
    criteria` section (pre-business) -- the caller decides whether that is fatal."""
    found, dims = story_dimensions(text)
    technical = _check_dimensions(cat, dims["tac"], DIMENSIONS) if found["tac"] else None
    business = _check_dimensions(cat, dims["bac"], BUSINESS_DIMENSIONS) if found["bac"] else None
    return technical, business


def all_story_files(ctx):
    ctx.need("impl")
    return sorted(glob.glob(os.path.join(ctx.impl, "epic-*", "sprint-*", "stories", "*.md")))


def cmd_check_pointers(ctx, a):
    cat = load_catalog(ctx)
    stories = all_story_files(ctx) if a.all else [ctx.abs(s) for s in a.story]
    broken, pre, pre_business = 0, [], []
    for s in stories:
        rel = ctx.rel(s)
        try:
            text = read_text(s)
        except (OSError, UnicodeDecodeError) as e:
            sys.stderr.write(f"{rel}: unreadable ({e})\n")
            broken += 1
            continue
        technical, business = check_story(cat, text)
        if technical is None:
            pre.append(rel)
            if not a.all:
                sys.stderr.write(f"{rel}: pre-provenance: no '## {TAC_HEADING}' section -- "
                                 f"treat it as thin and enrich it\n")
                broken += 1
            continue
        errs = list(technical)
        if business is None:
            pre_business.append(rel)
            msg = (f"{rel}: no '## {BAC_HEADING}' section -- "
                   f"state the outcome this story serves and its non-goals\n")
            if a.business == "required" and not a.all:
                sys.stderr.write(msg)
                broken += 1
                continue
            sys.stderr.write("INFO " + msg)
        else:
            errs += business
        for n, msg in errs:
            sys.stderr.write(f"{rel}:{n}: {msg}\n")
        broken += bool(errs)
    if a.all:
        for rel in pre:
            print(f"INFO pre-provenance: {rel}")
        for rel in pre_business:
            print(f"INFO pre-business: {rel}")
        if broken:
            print(f"check-pointers --all: {broken} story file(s) with broken pointers")
            return 1
        print(f"OK check-pointers --all: {len(stories)} story file(s), "
              f"{len(pre)} pre-provenance, {len(pre_business)} pre-business")
        return 0
    if broken:
        return 2
    print(f"OK check-pointers: {len(stories)} story file(s)")
    return 0


def cmd_sections(ctx, a):
    cat = load_catalog(ctx)
    seen = {}
    for s in a.stories:
        for _, _, value in story_pointers(read_text(ctx.abs(s))):
            hit, _ = resolve_pointer(cat, value)
            if hit is not None:
                seen[(hit[0], hit[1])] = hit[2]
    for (path, anchor), sec in sorted(seen.items(), key=lambda kv: (kv[0][0], kv[1].start)):
        print(f"{path}#{anchor} L{sec.start}–{sec.end}")
    if not seen:
        print("(no resolvable pointers)")
    return 0


# -- drift dispositions ----------------------------------------------------------------------- #

DISPOSITIONS = ("resolved-in-code", "adr-justified", "spec-updated", "spec-proposal")
SPEC_DISPOSITIONS = ("spec-updated", "spec-proposal")
# R1: epic findings AD-{n}; sprint findings SD-{sprint nn}-{n}, unique across an epic.
FINDING_ID_RE = re.compile(r"^(AD-\d+|SD-\d{2}-\d+)$")
SEVERITIES = ("BLOCKER", "MAJOR", "MINOR")
EXPECT_RE = re.compile(r"Blocker:\s*(\d+),\s*Major:\s*(\d+),\s*Minor:\s*(\d+)", re.IGNORECASE)
DISP_FILE = "drift-dispositions.yaml"


def _yaml():
    from ruamel.yaml import YAML
    y = YAML()
    y.width = 4096
    y.preserve_quotes = True
    return y


def load_yaml(path):
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as fh:
        return _yaml().load(fh)


def dump_yaml(path, data):
    import io
    buf = io.StringIO()
    _yaml().dump(data, buf)
    atomic_write(path, buf.getvalue())


def md_tables(text):
    """Every markdown table as a list of rows (header row first), cells as plain text."""
    tables, rows, row = [], None, None
    for t in md().parse(text):
        if t.type == "table_open":
            rows = []
        elif t.type == "tr_open" and rows is not None:
            row = []
        elif t.type in ("th_open", "td_open") and row is not None:
            row.append("")
        elif t.type == "inline" and row is not None and rows is not None:
            row[-1] = t.content.strip()
        elif t.type == "tr_close" and rows is not None:
            rows.append(row)
            row = None
        elif t.type == "table_close":
            tables.append(rows)
            rows = None
    return tables


def review_findings(path):
    """{id: {"severity", "title"}} from a review's findings table -- the shape
    l3io-arch-review's references/review-report.md prescribes, IDs in the `#` column."""
    try:
        text = read_text(path)
    except OSError as e:
        raise SAError(2, f"cannot read review {path}: {e.strerror or e}")
    out = {}
    for rows in md_tables(text):
        if not rows:
            continue
        head = [c.strip().casefold() for c in rows[0]]
        if "#" not in head or "severity" not in head:
            continue
        ci, si = head.index("#"), head.index("severity")
        ti = head.index("finding") if "finding" in head else None
        for r in rows[1:]:
            fid = r[ci].strip().strip("`") if ci < len(r) else ""
            if not FINDING_ID_RE.match(fid):
                continue
            if fid in out:
                raise SAError(2, f"{path}: finding {fid} appears twice")
            title = r[ti] if ti is not None and ti < len(r) and r[ti] else fid
            out[fid] = {"severity": r[si].strip().strip("*").upper(), "title": title}
    return out


def load_dispositions(dpath, review_rel=None):
    from ruamel.yaml.comments import CommentedMap
    data = load_yaml(dpath)
    if data is None:
        data = CommentedMap()
        data["review"] = review_rel
        data["findings"] = CommentedMap()
    if not isinstance(data.get("findings"), dict):
        raise SAError(2, f"{dpath}: 'findings' is not a mapping")
    return data


def cmd_disposition(ctx, a):
    from ruamel.yaml.comments import CommentedMap
    review = ctx.abs(a.review)
    f = review_findings(review).get(a.finding)
    if f is None:
        raise SAError(2, f"{a.finding} is not in the findings table of {ctx.rel(review)}")
    if a.spec_alignment.lower() != "true" and a.disposition in SPEC_DISPOSITIONS:
        raise SAError(2, f"spec_alignment is off: {a.finding} can only be resolved-in-code "
                         f"or adr-justified")
    spec = adr = None
    if a.adr:
        if not os.path.isfile(ctx.abs(a.adr)):
            raise SAError(2, f"--adr {a.adr} does not exist")
        adr = ctx.rel(ctx.abs(a.adr))
    elif a.disposition == "adr-justified":
        raise SAError(2, "adr-justified needs --adr naming the accepted ADR")
    if a.disposition in SPEC_DISPOSITIONS:
        if not a.spec:
            raise SAError(2, f"{a.disposition} needs --spec <path>#<anchor>")
        hit, why = resolve_pointer(load_catalog(ctx), a.spec)
        if hit is None:
            raise SAError(2, f"--spec {a.spec}: {why}")
        if a.disposition == "spec-updated" and hit[3] != "architecture":
            raise SAError(2, f"spec-updated edits architecture sections only; {hit[0]} is a "
                             f"{hit[3]} spec -- record spec-proposal instead (ADR-0004)")
        spec = f"{hit[0]}#{hit[1]}"
    dpath = os.path.join(os.path.dirname(review), DISP_FILE)
    data = load_dispositions(dpath, ctx.rel(review))
    prior = data["findings"].get(a.finding)
    if prior is not None and (prior.get("commit") or prior.get("issue")):
        raise SAError(2, f"{a.finding} was already applied "
                         f"({prior.get('commit') or prior.get('issue')}); its disposition "
                         f"cannot change")
    e = CommentedMap()
    e["severity"], e["title"], e["disposition"] = f["severity"], f["title"], a.disposition
    e["spec"], e["adr"], e["commit"], e["issue"] = spec, adr, None, None
    data["findings"][a.finding] = e
    dump_yaml(dpath, data)
    print(f"OK disposition {a.finding} ({f['severity']}) -> {a.disposition}")
    return 0


def cmd_check_dispositions(ctx, a):
    m = EXPECT_RE.search(a.expect)
    if not m:
        raise SAError(2, f"--expect {a.expect!r} has no 'Blocker: N, Major: N, Minor: N'")
    review = ctx.abs(a.review)
    findings = review_findings(review)
    expected = dict(zip(SEVERITIES, map(int, m.groups())))
    got = {s: sum(1 for f in findings.values() if f["severity"] == s) for s in SEVERITIES}
    problems = []
    odd = sorted({f["severity"] for f in findings.values()} - set(SEVERITIES))
    if odd:
        problems.append(f"unknown severities in the findings table: {', '.join(odd)}")
    if got != expected:
        problems.append(f"parsed Blocker: {got['BLOCKER']}, Major: {got['MAJOR']}, Minor: "
                        f"{got['MINOR']} from {ctx.rel(review)} but the reviewer reported "
                        f"Blocker: {expected['BLOCKER']}, Major: {expected['MAJOR']}, Minor: "
                        f"{expected['MINOR']} -- is the findings table in the "
                        f"references/review-report.md shape, IDs in the # column?")
    data = load_dispositions(os.path.join(os.path.dirname(review), DISP_FILE))
    for fid, f in sorted(findings.items()):
        if f["severity"] in ("BLOCKER", "MAJOR") and fid not in data["findings"]:
            problems.append(f"{fid} ({f['severity']}) has no disposition")
    for p in problems:
        sys.stderr.write(f"check-dispositions: {p}\n")
    if problems:
        return 2
    print(f"OK check-dispositions: {len(findings)} finding(s), every BLOCKER/MAJOR disposed")
    return 0


# -- ADRs (one home: docs/adr/, ADR-0005) ------------------------------------------------------- #

# The `ADR-` prefix is optional on the one home and case-insensitive on both, because
# `docs/adr/` also holds hand-written ADRs and `ADR-NNNN-slug.md` is a common naming
# convention that matched neither. Group 2 stays the slug in every accepted spelling,
# so `_migration_plan`'s same-number-same-slug duplicate test is unaffected.
DOC_ADR_RE = re.compile(r"^(?:[Aa][Dd][Rr]-)?(\d{4})-(.+)\.md$")  # group 2 = slug: see _migration_plan
LEGACY_ADR_RE = re.compile(r"^[Aa][Dd][Rr]-(\d{4})-(.+)\.md$")
ADR_META_RE = re.compile(r"^-\s+\*\*(Status|Epic|Departs from spec):\*\*\s*(.*?)\s*$")


def epic_key(value):
    """'E003', 'e3', '003', '3' -> 'E003'; anything else (n/a, empty) -> None."""
    m = re.fullmatch(r"\s*E?(\d{1,3})\s*", str(value or ""), re.IGNORECASE)
    return f"E{int(m.group(1)):03d}" if m else None


def adr_meta(path):
    """The metadata bullets before the first `##` heading (assets/adr-template.md shape)."""
    meta = {}
    for line in read_text(path).splitlines():
        if line.startswith("## "):
            break
        m = ADR_META_RE.match(line)
        if m:
            meta[m.group(1)] = m.group(2).strip().strip("`")
    return meta


def all_adrs(ctx):
    out = []
    docs = os.path.join(ctx.project, "docs", "adr")
    if os.path.isdir(docs):
        for name in sorted(os.listdir(docs)):
            m = DOC_ADR_RE.match(name)
            if m:
                p = os.path.join(docs, name)
                meta = adr_meta(p)
                out.append({"path": ctx.rel(p), "number": int(m.group(1)), "home": "docs",
                            "epic": epic_key(meta.get("Epic")), "status": meta.get("Status", ""),
                            "departs": meta.get("Departs from spec", "")})
    if ctx.impl:
        for p in sorted(glob.glob(os.path.join(ctx.impl, "epic-*", "arch", "adr-*.md"))):
            m = LEGACY_ADR_RE.match(os.path.basename(p))
            em = re.search(r"epic-(\d{3})", os.path.basename(os.path.dirname(os.path.dirname(p))))
            if m and em:
                meta = adr_meta(p)
                out.append({"path": ctx.rel(p), "number": int(m.group(1)), "home": "legacy",
                            "epic": f"E{em.group(1)}", "status": meta.get("Status", ""),
                            "departs": meta.get("Departs from spec", "")})
    return out


def link_gaps(ctx, cat, adrs):
    """Accepted ADRs whose `Departs from spec:` section does not link back to them."""
    gaps = []
    for x in adrs:
        dep = (x["departs"] or "").strip()
        if not x["status"].lower().startswith("accepted") or not dep or dep.lower() == "n/a":
            continue
        if not PTR_RE.match(dep):
            gaps.append((x, dep, "not a pointer"))
            continue
        hit, _ = resolve_pointer(cat, dep)
        if hit is None:
            gaps.append((x, dep, "pointer does not resolve"))
            continue
        sec = hit[2]
        body = read_text(ctx.abs(hit[0])).splitlines()[sec.start - 1:sec.end]
        if not any(os.path.basename(x["path"]) in line for line in body):
            gaps.append((x, dep, "section does not link the ADR"))
    return gaps


def cmd_adrs(ctx, a):
    ek = epic_key(a.epic)
    if ek is None:
        raise SAError(2, f"--epic {a.epic!r} is not an epic key")
    rows = [x for x in all_adrs(ctx) if x["epic"] == ek]
    for x in rows:
        if x["home"] == "legacy":
            sys.stderr.write(f"WARN {x['path']} is in the old ADR home -- run "
                             f"/l3io-doctor migrate-adrs\n")
    if a.format == "json":
        print(json.dumps(rows, indent=2))
    else:
        for x in rows:
            print(x["path"])
    return 0


def cmd_check_links(ctx, a):
    adrs = all_adrs(ctx)
    if a.epic:
        ek = epic_key(a.epic)
        if ek is None:
            raise SAError(2, f"--epic {a.epic!r} is not an epic key")
        adrs = [x for x in adrs if x["epic"] == ek]
    gaps = link_gaps(ctx, load_catalog(ctx), adrs)
    for x, dep, why in gaps:
        print(f"{x['path']}: departs from {dep} -- {why}")
    if gaps:
        return 1
    print(f"OK check-links: {len(adrs)} ADR(s)")
    return 0


# -- the spec-sync lease ---------------------------------------------------------------------- #
# Parallel epic closures share one working tree: without a lease two agents can edit one
# architecture doc at once, or one commits the other's half-made edit. It is a lease, not a
# flock, because it must survive an agent's many turns; the flock only guards the file's
# read-decide-write. The `.lock` name puts it under pm-status's `*.lock` rule in
# state/.gitignore, which exists by epic closure (every set-status takes an epic lock there).

LEASE_NAME = "spec-sync.lock"


class LeaseHeld(Exception):
    pass


def _now():
    from datetime import datetime
    return datetime.now(UTC)


def _iso(dt):
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _parse_iso(s):
    from datetime import datetime
    try:
        return datetime.strptime(str(s), "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=UTC)
    except ValueError:
        return None


def _lease_path(ctx):
    ctx.need("state")
    os.makedirs(ctx.state_root, exist_ok=True)
    return os.path.join(ctx.state_root, LEASE_NAME)


def _lease_read(fh):
    fh.seek(0)
    raw = fh.read().strip()
    if not raw:
        return None
    try:
        cur = json.loads(raw)
    except ValueError:
        sys.stderr.write(f"WARN {LEASE_NAME} is not JSON; treating the lease as free\n")
        return None
    return cur if isinstance(cur, dict) else None


def _lease_write(fh, value):
    fh.seek(0)
    fh.truncate()
    if value is not None:
        fh.write(json.dumps(value))
    fh.flush()
    os.fsync(fh.fileno())


def lease_holder(ctx):
    """The current lease if it is held and unexpired, else None."""
    import fcntl
    path = _lease_path(ctx)
    if not os.path.exists(path):
        return None
    with open(path, "a+", encoding="utf-8") as fh:
        fcntl.flock(fh, fcntl.LOCK_SH)
        try:
            cur = _lease_read(fh)
        finally:
            fcntl.flock(fh, fcntl.LOCK_UN)
    if cur and (_parse_iso(cur.get("expires_at")) or _now()) > _now():
        return cur
    return None


def _lease_try(path, owner, ttl_minutes):
    import fcntl
    from datetime import timedelta
    with open(path, "a+", encoding="utf-8") as fh:
        fcntl.flock(fh, fcntl.LOCK_EX)
        try:
            cur, now = _lease_read(fh), _now()
            if cur and cur.get("owner") != owner:
                expires = _parse_iso(cur.get("expires_at"))
                if expires is not None and expires > now:
                    raise LeaseHeld(cur)
                sys.stderr.write(f"WARN spec-sync lease held by {cur.get('owner')} expired at "
                                 f"{cur.get('expires_at')}; taking it over\n")
            new = {"owner": owner, "acquired_at": _iso(now),
                   "expires_at": _iso(now + timedelta(minutes=ttl_minutes))}
            _lease_write(fh, new)
            return new
        finally:
            fcntl.flock(fh, fcntl.LOCK_UN)


def cmd_lease(ctx, a):
    import fcntl
    owner = epic_key(a.owner)
    if owner is None:
        raise SAError(2, f"--owner {a.owner!r} is not an epic key")
    path = _lease_path(ctx)
    if a.lease_cmd == "acquire":
        from tenacity import retry, retry_if_exception_type, stop_after_delay, wait_fixed

        @retry(retry=retry_if_exception_type(LeaseHeld), reraise=True,
               stop=stop_after_delay(a.wait_minutes * 60), wait=wait_fixed(a.poll_seconds))
        def attempt():
            return _lease_try(path, owner, a.ttl_minutes)

        try:
            new = attempt()
        except LeaseHeld as e:
            cur = e.args[0]
            sys.stderr.write(f"spec-sync lease held by {cur.get('owner')} until "
                             f"{cur.get('expires_at')}\n")
            return 5
        print(f"OK lease acquired by {owner} until {new['expires_at']}")
        return 0
    with open(path, "a+", encoding="utf-8") as fh:
        fcntl.flock(fh, fcntl.LOCK_EX)
        try:
            cur = _lease_read(fh)
            if not cur:
                print("OK lease already free")
                return 0
            if cur.get("owner") != owner:
                raise SAError(2, f"the lease is held by {cur.get('owner')}, not {owner}")
            _lease_write(fh, None)
        finally:
            fcntl.flock(fh, fcntl.LOCK_UN)
    print(f"OK lease released by {owner}")
    return 0


# -- spec sync: the plan, deferral, proposals ---------------------------------------------- #

SEV_MAP = {"BLOCKER": "High", "MAJOR": "Medium", "MINOR": "Low"}
ISSUE_KEY_RE = re.compile(r"\b(BL-E\d{3}-\d{3})\b")


def _pm(ctx, *args):
    ctx.need("pm")
    return subprocess.run([sys.executable, ctx.pm_status, *args], capture_output=True, check=False, text=True)


def _spec_issue_args(ctx, nnn, kind, ref, ident, title, severity, pointer, where):
    label = "Spec change" if kind == "spec-change" else "Spec proposal"
    return ["append-issue", "--state-root", ctx.state_root, "--epic", nnn, "--sprint", "",
            "--kind", kind, "--ref", ref, "--title", f"{label}: {title}",
            "--source", f"spec-sync ({ident})", "--severity", SEV_MAP.get(severity, "Low"),
            "--description", (f"Confirm or reject: /l3io-doctor triage. Spec: {pointer}. "
                             f"From: {where}.")]


def append_spec_issue(ctx, nnn, kind, ref, ident, title, severity, pointer, where):
    """One spec-change/spec-proposal backlog item through pm-status; returns its key. A rerun
    after a crash finds the open twin (append-issue skips a content duplicate and names it)."""
    ctx.need("state")
    args = _spec_issue_args(ctx, nnn, kind, ref, ident, title, severity, pointer, where)
    r = _pm(ctx, *args)
    if r.returncode == 0 and "resolved as" in r.stdout:     # matched a resolved twin, not open
        r = _pm(ctx, *args, "--allow-duplicate")
    m = ISSUE_KEY_RE.search(r.stdout)
    if r.returncode != 0 or not m:
        raise SAError(2, f"append-issue failed: {(r.stderr or r.stdout).strip()}")
    return m.group(1)


def epic_nnn(value):
    ek = epic_key(value)
    if ek is None:
        raise SAError(2, f"--epic {value!r} is not an epic key")
    return ek[1:]


def epic_disp_path(ctx, nnn):
    ctx.need("impl")
    return os.path.join(ctx.impl, f"epic-{nnn}", "epic-closure", DISP_FILE)


def disposition_files(ctx, nnn):
    ctx.need("impl")
    files = sorted(glob.glob(os.path.join(ctx.impl, f"epic-{nnn}", "sprint-*", "closure",
                                          DISP_FILE)))
    ep = epic_disp_path(ctx, nnn)
    return files + ([ep] if os.path.isfile(ep) else [])


def proposal_path(ctx, nnn, ident):
    return os.path.join(ctx.impl, f"epic-{nnn}", "epic-closure", "spec-proposals", f"{ident}.md")


def adr_ident(ctx, path):
    m = DOC_ADR_RE.match(os.path.basename(path))
    if not m or not os.path.isfile(ctx.abs(path)):
        raise SAError(2, f"--adr {path} is not an ADR under docs/adr/")
    return f"ADR-{int(m.group(1)):04d}"


def _range(hit):
    return f"L{hit[2].start}–{hit[2].end}" if hit else None


def pending_items(ctx, nnn, cat):
    items = []
    for f in disposition_files(ctx, nnn):
        data = load_dispositions(f)
        for fid, e in data["findings"].items():
            if (e.get("disposition") not in SPEC_DISPOSITIONS or e.get("commit")
                    or e.get("issue")):
                continue
            hit, why = resolve_pointer(cat, e.get("spec") or "")
            items.append({"type": e["disposition"], "id": fid, "severity": e.get("severity"),
                          "title": e.get("title"), "spec": e.get("spec"), "range": _range(hit),
                          "problem": why, "adr": e.get("adr"), "review": data.get("review"),
                          "dispositions": ctx.rel(f)})
    ep = epic_disp_path(ctx, nnn)
    done = (load_yaml(ep) or {}).get("adr_links") or {}
    for x, dep, why in link_gaps(ctx, cat, [a for a in all_adrs(ctx) if a["epic"] == f"E{nnn}"]):
        ident = f"ADR-{x['number']:04d}"
        if why != "section does not link the ADR" or ident in done:
            continue
        hit, _ = resolve_pointer(cat, dep)
        items.append({"type": "adr-link", "id": ident, "severity": "MINOR",
                      "title": f"Link {ident} from {dep}", "spec": dep, "range": _range(hit),
                      "problem": None, "adr": x["path"], "review": None,
                      "dispositions": ctx.rel(ep)})
    return items


def find_item(ctx, nnn, ident, cat):
    hits = [i for i in pending_items(ctx, nnn, cat) if i["id"] == ident]
    if not hits:
        raise SAError(2, f"{ident} is not a pending spec item for E{nnn} (see sync-plan)")
    return hits[0]


def record_item(ctx, item, **fields):
    from ruamel.yaml.comments import CommentedMap
    dpath = ctx.abs(item["dispositions"])
    data = load_dispositions(dpath)
    if item["type"] == "adr-link":
        if data.get("adr_links") is None:
            data["adr_links"] = CommentedMap()
        entry = data["adr_links"].get(item["id"])
        if entry is None:
            entry = data["adr_links"][item["id"]] = CommentedMap()
    else:
        entry = data["findings"][item["id"]]
    for k, v in fields.items():
        entry[k] = v
    dump_yaml(dpath, data)


def _deferred_text(it):
    lines = [f"# Spec proposal — {it['id']} (deferred)", "",
             f"- **Finding:** {it['id']}" + (f" in `{it['review']}`" if it["review"] else ""),
             f"- **Severity:** {it['severity']}",
             f"- **Spec:** `{it['spec']}` ({it['range'] or 'pointer does not resolve'})"]
    if it["adr"]:
        lines.append(f"- **ADR:** `{it['adr']}`")
    lines += [("- **Why deferred:** the spec-sync lease was held by another epic's closure, so "
              "nothing was edited."), "",
              ("Apply the change the finding describes to that section, then confirm this item "
              "in `/l3io-doctor triage`."), ""]
    return "\n".join(lines)


def cmd_sync_plan(ctx, a):
    nnn = epic_nnn(a.epic)
    items = pending_items(ctx, nnn, load_catalog(ctx))
    if not a.defer:
        print(json.dumps({"epic": f"E{nnn}", "items": items}, indent=2))
        return 0
    done = []
    for it in items:
        rel = ctx.rel(proposal_path(ctx, nnn, it["id"]))
        atomic_write(ctx.abs(rel), _deferred_text(it))
        key = append_spec_issue(ctx, nnn, "spec-proposal", rel, it["id"], it["title"],
                                it["severity"], it["spec"], it["review"] or it["adr"])
        fields = {"proposal": rel, "issue": key}
        if it["type"] != "adr-link":
            fields.update(disposition="spec-proposal", deferred=True)     # R10
        record_item(ctx, it, **fields)
        done.append({"id": it["id"], "proposal": rel, "issue": key})
    print(json.dumps({"epic": f"E{nnn}", "deferred": done}, indent=2))
    return 0


def cmd_propose(ctx, a):
    nnn = epic_nnn(a.epic)
    ident = a.finding or adr_ident(ctx, a.adr)
    it = find_item(ctx, nnn, ident, load_catalog(ctx))
    rel = ctx.rel(proposal_path(ctx, nnn, ident))
    p = ctx.abs(rel)
    if not os.path.isfile(p) or not read_text(p).strip():
        raise SAError(2, f"write the proposal at {rel} first (target pointer, the change, why, "
                         f"and the finding)")
    key = append_spec_issue(ctx, nnn, "spec-proposal", rel, ident, it["title"], it["severity"],
                            it["spec"], it["review"] or it["adr"])
    fields = {"proposal": rel, "issue": key}
    if it["type"] == "spec-updated":
        fields["disposition"] = "spec-proposal"
    record_item(ctx, it, **fields)
    print(f"OK propose {ident} -> {key} ({rel})")
    return 0


# -- git and the guarded docs(spec) commit ----------------------------------------------------- #

class IndexLocked(Exception):
    pass


def _git(ctx, *args, check=True):
    try:
        r = subprocess.run(["git", "-C", ctx.project, *args], capture_output=True, check=False, text=True)
    except OSError as e:
        raise SAError(2, f"git is not available: {e}")
    if check and r.returncode != 0:
        raise SAError(2, f"git {' '.join(args)} failed: {(r.stderr or r.stdout).strip()}")
    return r


def git_commit(ctx, message, paths):
    """`git commit -s --only -- paths`: exactly those paths, even in a checkout other agents
    share. A held index.lock is retried with backoff (tenacity), then refused."""
    from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_exponential

    @retry(retry=retry_if_exception_type(IndexLocked), reraise=True,
           stop=stop_after_attempt(5), wait=wait_exponential(multiplier=0.2, max=2))
    def attempt():
        r = _git(ctx, "commit", "-s", "--only", "-m", message, "--", *paths, check=False)
        if r.returncode != 0:
            err = (r.stderr or r.stdout).strip()
            if "index.lock" in err:
                raise IndexLocked(err)
            raise SAError(2, f"git commit failed: {err}")

    try:
        attempt()
    except IndexLocked as e:
        raise SAError(2, f"the git index stayed locked after 5 attempts: {e}")
    return _git(ctx, "rev-parse", "HEAD").stdout.strip()


def changed_hunks(ctx, rel):
    from unidiff import PatchSet
    diff = _git(ctx, "diff", "-U0", "HEAD", "--", rel).stdout
    if not diff.strip():
        return []
    return [(h.source_start, h.source_length) for pf in PatchSet(diff) for h in pf]


def hunks_outside(hunks, sec):
    """Hunks (in HEAD line numbers) not contained in the section. A pure insertion
    (length 0) lands after line `start`, which must itself be inside the section."""
    bad = []
    for start, length in hunks:
        inside = (sec.start <= start <= sec.end) if length == 0 else (
            sec.start <= start and start + length - 1 <= sec.end)
        if not inside:
            bad.append((start, length))
    return bad


def _pointer_re(rel, anchor):
    return re.compile(rf"^(\s*(?:[-*]\s+)?Spec:\s*){re.escape(rel)}#{re.escape(anchor)}(\s*)$",
                      re.MULTILINE)


def pointing_stories(ctx, rel, anchor):
    pat = _pointer_re(rel, anchor)
    return [s for s in all_story_files(ctx) if pat.search(read_text(s))]


def rewrite_pointer(path, rel, old, new):
    pat = _pointer_re(rel, old)
    atomic_write(path, pat.sub(lambda m: f"{m.group(1)}{rel}#{new}{m.group(2)}",
                               read_text(path)))


def adr_link_item(ctx, nnn, path):
    """The adr-link item for an ADR, built from its own metadata -- not from sync-plan, whose
    gap disappears the moment the agent has written the link this commit is for."""
    ident = adr_ident(ctx, path)
    rows = [x for x in all_adrs(ctx) if x["path"] == ctx.rel(ctx.abs(path))]
    if not rows or rows[0]["epic"] != f"E{nnn}":
        raise SAError(2, f"{path} is not an ADR of E{nnn} (its Epic: line)")
    dep = (rows[0]["departs"] or "").strip()
    if not PTR_RE.match(dep):
        raise SAError(2, f"{path} has no `Departs from spec:` pointer to link from")
    cat = load_catalog(ctx)
    hit, why = resolve_pointer(cat, dep)
    if hit is None:
        raise SAError(2, f"{path}: `Departs from spec:` {dep} does not resolve ({why})")
    if hit[3] != "architecture":
        raise SAError(2, f"{path} departs from {hit[0]}, a {hit[3]} spec; agents edit "
                         f"architecture specs only (docs/adr/0004-agents-edit-architecture-"
                         f"specs.md) -- add the {ident} link there by hand")
    if ident in ((load_yaml(epic_disp_path(ctx, nnn)) or {}).get("adr_links") or {}):
        raise SAError(2, f"{ident} is already linked or proposed for E{nnn}")
    return {"type": "adr-link", "id": ident, "severity": "MINOR",
            "title": f"Link {ident} from {dep}", "spec": dep, "adr": rows[0]["path"],
            "review": None, "dispositions": ctx.rel(epic_disp_path(ctx, nnn))}


def cmd_commit(ctx, a):
    ctx.need("impl", "state", "pm")
    nnn = epic_nnn(a.epic)
    holder = lease_holder(ctx)
    if not holder or holder.get("owner") != f"E{nnn}":
        raise SAError(2, f"the spec-sync lease is not held by E{nnn} -- run "
                         f"`lease acquire --owner E{nnn}` first")
    if a.finding:
        item = find_item(ctx, nnn, a.finding, load_catalog(ctx))
        if item["type"] != "spec-updated":
            raise SAError(2, f"{a.finding} is a {item['type']} item: proposals are never "
                             f"edited -- write the proposal and run `propose`")
    else:
        item = adr_link_item(ctx, nnn, a.adr)
    ident = item["id"]
    rel, anchor = PTR_RE.match(item["spec"]).groups()
    if [ctx.rel(ctx.abs(p)) for p in a.paths] != [rel]:
        raise SAError(2, f"--paths must be exactly {rel}, the file {ident} points at")
    head = _git(ctx, "show", f"HEAD:{rel}", check=False)
    if head.returncode != 0:
        raise SAError(2, f"{rel} is not committed at HEAD; spec sync edits committed specs only")
    head_secs = {s.anchor: s for s in parse_sections(head.stdout)}
    sec = head_secs.get(anchor)
    if sec is None:
        raise SAError(2, f"{rel} has no #{anchor} at HEAD")
    hunks = changed_hunks(ctx, rel)
    if not hunks:
        raise SAError(2, f"{rel} has no change to commit")
    bad = hunks_outside(hunks, sec)
    if bad:
        spots = ", ".join(f"L{s}" + (f"–{s + n - 1}" if n > 1 else "") for s, n in bad)
        raise SAError(2, f"the edit to {rel} changes line(s) outside #{anchor} "
                         f"(L{sec.start}–{sec.end} at HEAD): {spots} -- edit only that section")
    work = parse_sections(read_text(ctx.abs(rel)))
    after = {s.anchor for s in work}
    renames = {}
    for pair in a.rename_anchor:
        old, _, new = pair.partition("=")
        if not old or not new or new not in after:
            raise SAError(2, f"--rename-anchor {pair}: {new or '(empty)'} is not an anchor in "
                             f"the edited {rel}")
        renames[old] = new
    unhandled = {}
    for gone in sorted(set(head_secs) - after):
        stories = pointing_stories(ctx, rel, gone)
        if stories and gone not in renames:
            unhandled[gone] = [ctx.rel(s) for s in stories]
    if unhandled:
        detail = "; ".join(f"#{k} <- {', '.join(v)}" for k, v in unhandled.items())
        raise SAError(2, f"the edit removes anchor(s) stories point to: {detail} -- keep the "
                         f"heading, or pass --rename-anchor OLD=NEW to rewrite those pointers")
    target = renames.get(anchor, anchor)
    if item["type"] == "adr-link":
        wsec = next((s for s in work if s.anchor == target), None)
        body = read_text(ctx.abs(rel)).splitlines()[wsec.start - 1:wsec.end] if wsec else []
        link_re = re.compile(r"\[[^\]]*\]\((?:[^)]*/)?"
                             + re.escape(os.path.basename(item["adr"])) + r"\)")
        if not any(link_re.search(line) for line in body):
            raise SAError(2, f"the edit does not link {item['adr']} from #{target} "
                             f"(a markdown link to it, not a mention of its filename)")
    paths = [rel]
    rewritten = []
    for old, new in renames.items():
        for s in pointing_stories(ctx, rel, old):
            rewrite_pointer(s, rel, old, new)
            rewritten.append((s, old, new))
            paths.append(ctx.rel(s))
    message = (f"docs(spec): E{nnn} {ident} — {item['title']}" if item["type"] == "spec-updated"
               else f"docs(spec): E{nnn} link {ident} from {item['spec']}")
    try:
        sha = git_commit(ctx, message, paths)
    except Exception:
        # The spec edit and its pointer rewrites must land in one commit or none, so a failed
        # commit (e.g. a stuck index.lock) must not strand the rewrites: undo them here, not
        # via `git restore`/`git checkout`, which would also discard unrelated uncommitted
        # edits already sitting in those story files.
        for s, old, new in reversed(rewritten):
            rewrite_pointer(s, rel, new, old)
        raise
    fields = {"commit": sha}
    if target != anchor and item["type"] == "spec-updated":
        fields["spec"] = f"{rel}#{target}"
        item["spec"] = fields["spec"]
    record_item(ctx, item, **fields)
    try:
        key = append_spec_issue(ctx, nnn, "spec-change", sha, ident, item["title"],
                                item["severity"], item["spec"], item["review"] or item["adr"])
    except SAError as e:
        args = _spec_issue_args(ctx, nnn, "spec-change", sha, ident, item["title"],
                                item["severity"], item["spec"], item["review"] or item["adr"])
        cmd = " ".join(shlex.quote(x) for x in [ctx.pm_status, *args])
        raise SAError(2, f"{e}; commit {sha} already landed and is recorded on {ident}'s "
                         f"disposition -- finish recording the backlog issue by hand: {cmd}")
    record_item(ctx, item, issue=key)
    print(f"OK commit {sha[:12]} {ident} -> {key}")
    return 0


# -- confirm/reject support ------------------------------------------------------------------- #

def _open_items(ctx, *extra):
    ctx.need("state", "pm")
    r = _pm(ctx, "list-issues", "--state-root", ctx.state_root, "--format", "json", *extra)
    if r.returncode != 0:
        raise SAError(2, f"list-issues failed: {(r.stderr or r.stdout).strip()}")
    return json.loads(r.stdout or "[]")


def cmd_reject(ctx, a):
    it = next((i for i in _open_items(ctx) if i.get("key") == a.key), None)
    if it is None:
        raise SAError(2, f"{a.key} is not an open backlog item")
    kind = it.get("kind") or "defect"
    if kind not in ("spec-change", "spec-proposal"):
        raise SAError(2, f"{a.key} is a {kind} item; reject handles spec-change and "
                         f"spec-proposal items only")
    ref = str(it.get("ref") or "")
    if kind == "spec-change":
        r = _git(ctx, "revert", "--no-edit", "--signoff", ref, check=False)
        if r.returncode != 0:
            unmerged = [l for l in _git(ctx, "diff", "--name-only", "--diff-filter=U",
                                        check=False).stdout.splitlines() if l]
            _git(ctx, "revert", "--abort", check=False)
            raise SAError(2, f"git revert {ref} failed (unmerged: "
                             f"{', '.join(unmerged) or 'none reported'}); aborted the revert, "
                             f"{a.key} stays open. Resolve by hand, then resolve it.")
        res_ref = _git(ctx, "rev-parse", "HEAD").stdout.strip()
    else:
        res_ref = ref
    r = _pm(ctx, "resolve-issue", "--state-root", ctx.state_root, "--key", a.key,
            "--resolution", "wontfix", "--ref", res_ref, "--note",
            f"{kind} rejected in triage", "--cause", "triage")
    if r.returncode != 0:
        raise SAError(2, f"resolve-issue failed after {res_ref}: "
                         f"{(r.stderr or r.stdout).strip()}")
    title = re.sub(r"^Spec (change|proposal):\s*", "", str(it.get("title", "")))
    args = ["append-issue", "--state-root", ctx.state_root, "--epic", str(it.get("epic", "")),
            "--sprint", "", "--title", f"Code diverges from spec: {title}",
            "--source", f"spec-reject ({a.key})", "--severity", str(it.get("severity") or "Medium"),
            "--description", (f"{kind} {a.key} was rejected, so the code must change to match "
                              f"the spec. {it.get('description') or ''}").strip()]
    r = _pm(ctx, *args)
    m = ISSUE_KEY_RE.search(r.stdout)
    if r.returncode != 0 or not m:
        cmd = " ".join(shlex.quote(x) for x in [ctx.pm_status, *args])
        raise SAError(2, f"{a.key} is resolved but the code fix was not filed -- rerun: {cmd}")
    print(f"OK reject {a.key} ({kind}) -> wontfix {res_ref}; code fix {m.group(1)}")
    return 0


def cmd_check_stale(ctx, a):
    items = _open_items(ctx, "--kind", "spec-change")
    findings = []
    for it in items:
        ref = str(it.get("ref") or "")
        if not ref:
            continue                                  # audit-issues 1k reports a missing ref
        files = [l for l in _git(ctx, "show", "--name-only", "--format=", ref,
                                 check=False).stdout.splitlines() if l]
        if not files:
            findings.append(f"{it['key']}: its commit {ref} is not in this repository")
            continue
        later = _git(ctx, "log", "--format=%h", f"{ref}..HEAD", "--", *files,
                     check=False).stdout.split()
        if later:
            ct = _git(ctx, "show", "-s", "--format=%ct", ref, check=False).stdout.strip()
            age = f"{(time.time() - int(ct)) / 86400:.0f} day(s) old, " if ct.isdigit() else ""
            findings.append(f"{it['key']}: unconfirmed spec change {ref[:12]} ({age}"
                            f"{len(later)} later commit(s) on {', '.join(files)}) -- confirm "
                            f"or reject it in /l3io-doctor triage")
    for f in findings:
        print(f)
    if findings:
        return 1
    print(f"OK check-stale: {len(items)} unconfirmed spec change(s), none built upon")
    return 0


# -- migrate-adrs: the old per-epic home -> docs/adr (ADR-0005) ------------------------------- #

def _migration_plan(ctx):
    ctx.need("impl", "state")
    docs_dir = os.path.join(ctx.project, "docs", "adr")
    docs_by_num = {}
    if os.path.isdir(docs_dir):
        docs_by_num = {int(m.group(1)): m.group(2)
                       for m in map(DOC_ADR_RE.match, os.listdir(docs_dir)) if m}
    docs_nums = set(docs_by_num)
    moves, taken = [], set(docs_nums)
    for p in sorted(glob.glob(os.path.join(ctx.impl, "epic-*", "arch", "adr-*.md"))):
        m = LEGACY_ADR_RE.match(os.path.basename(p))
        em = re.search(r"epic-(\d{3})", os.path.basename(os.path.dirname(os.path.dirname(p))))
        if not (m and em):
            continue
        n, slug = int(m.group(1)), m.group(2)
        # A same-number AND same-slug file in docs/adr is not a competing decision -- it IS
        # this decision, already migrated, and the epic copy is a leftover (often a stale
        # pre-supersession snapshot). Renumbering it mints a duplicate ADR under a fresh
        # number and rewrites the epic's artifacts to cite the invented one. Observed on a
        # real project: all 14 legacy ADRs were duplicates, so every single one would have
        # been minted as new. Only a DIFFERENT slug is a genuine collision.
        dup = docs_by_num.get(n) == slug
        moves.append({"from": ctx.rel(p), "number": n, "slug": slug, "epic": f"E{em.group(1)}",
                      "duplicate": dup,
                      "collision": (n in taken) and not dup,
                      "to": None if n in taken else f"docs/adr/{n:04d}-{slug}.md"})
        taken.add(n)
    reg = load_yaml(os.path.join(ctx.state_root, "adr-register.yaml")) or {}
    try:
        nxt = int(reg.get("next", 1))
    except (TypeError, ValueError):
        nxt = 1
    hi = max([*docs_nums, *(mv["number"] for mv in moves)], default=0)
    return {"moves": moves,
            "duplicates": [mv for mv in moves if mv["duplicate"]],
            "actionable": [mv for mv in moves if not mv["duplicate"]],
            "register": {"next": nxt, "highest_on_disk": hi, "lagging": hi > 0 and nxt <= hi},
            "rewritten": [], "rewritten_uncommitted": [], "review": [], "commit": None}


def _add_epic_line(text, ek):
    if re.search(r"^-\s+\*\*Epic:\*\*", text, re.MULTILINE):
        return text
    text2, n = re.subn(r"^(-\s+\*\*Status:\*\*.*)$", rf"\1\n- **Epic:** {ek}", text,
                       count=1, flags=re.MULTILINE)
    return text2 if n else re.sub(r"^(#[^\n]*\n)", rf"\1\n- **Epic:** {ek}\n", text, count=1)


def cmd_migrate_adrs(ctx, a):
    plan = _migration_plan(ctx)
    # A duplicate is reported, never moved: nothing for --apply to do about it. When every
    # move is a duplicate there is no work at all, and proceeding would open a git
    # transaction that commits nothing.
    if a.plan or not plan["actionable"]:
        print(json.dumps(plan, indent=2))
        return 0
    if _git(ctx, "rev-parse", "--is-inside-work-tree", check=False).stdout.strip() != "true":
        raise SAError(2, "migrate-adrs --apply needs a git work tree")
    docs_dir = os.path.join(ctx.project, "docs", "adr")
    md_files = sorted(set(glob.glob(os.path.join(ctx.impl, "**", "*.md"), recursive=True)))
    # Pre-flight: refuse if any path this run would touch already has uncommitted changes.
    # A previous --apply that stopped partway (adr-reserve, git mv, or the process itself
    # failing) leaves the tree mutated with nothing committed; a rerun's _migration_plan no
    # longer sees the already-moved files (they left epic-*/arch/), so it would quietly plan
    # less work over stray state instead of surfacing it. This is what stops that compounding.
    # The loop below can rewrite a *.md file in ANY epic (an exact path reference to the
    # moved ADR, or -- when renumbering -- a bare ADR-NNNN mention inside the moving ADR's own
    # epic tree), not only files under the source epic-*/arch/ or its own tree, so those
    # matching files are checked individually rather than assumed clean.
    check_paths = {ctx.rel(docs_dir)}
    for mv in plan["actionable"]:
        nnn, old, slug = mv["epic"][1:], mv["number"], mv["slug"]
        check_paths.add(os.path.dirname(mv["from"]))                       # its epic-*/arch/
        check_paths.add(f"{ctx.rel(ctx.impl)}/epic-{nnn}")                  # its own epic tree
        path_re = re.compile(rf"[\w./-]*epic-{nnn}/arch/adr-{old:04d}-{re.escape(slug)}\.md")
        for f in md_files:
            if os.path.isfile(f) and path_re.search(read_text(f)):
                check_paths.add(ctx.rel(f))                                # any file naming it
        if mv["collision"]:
            num_re = re.compile(rf"\bADR-{old:04d}\b")
            epic_tree = os.path.join(ctx.impl, f"epic-{nnn}")
            for f in md_files:
                if (os.path.isfile(f) and _under(f, epic_tree)
                        and num_re.search(read_text(f))):
                    check_paths.add(ctx.rel(f))                            # renumber target
    dirty = _git(ctx, "status", "--porcelain", "--", *sorted(check_paths), check=False).stdout
    if dirty.strip():
        raise SAError(2, "migrate-adrs --apply refuses: uncommitted changes already sit under "
                         f"{', '.join(sorted(check_paths))} -- a previous run may have stopped "
                         f"midway. Inspect and commit or revert those paths by hand (never a "
                         f"repo-wide discard; other agents share this checkout), then retry:\n"
                         f"{dirty}")
    os.makedirs(docs_dir, exist_ok=True)
    other_docs = sorted(glob.glob(os.path.join(ctx.project, "docs", "**", "*.md"),
                                  recursive=True))
    commit_paths, rewritten, touched = [], set(), []
    try:
        for mv in plan["actionable"]:
            old, nnn = mv["number"], mv["epic"][1:]
            new = old
            if mv["collision"]:
                r = _pm(ctx, "adr-reserve", "--state-root", ctx.state_root, "--epic", mv["epic"],
                        "--slug", f"migrate-{mv['slug']}", "--adr-dir", docs_dir)
                if r.returncode != 0 or not r.stdout.split():
                    raise SAError(2, f"adr-reserve failed: {(r.stderr or r.stdout).strip()}")
                new = int(r.stdout.split()[0])
                mv["renumbered_to"] = new
                mv["to"] = f"docs/adr/{new:04d}-{mv['slug']}.md"
            tracked = _git(ctx, "ls-files", "--error-unmatch", "--", mv["from"],
                           check=False).returncode == 0
            if tracked:
                _git(ctx, "mv", "--", mv["from"], mv["to"])
                commit_paths += [mv["from"], mv["to"]]
            else:
                os.replace(ctx.abs(mv["from"]), ctx.abs(mv["to"]))
                _git(ctx, "add", "--", mv["to"])
                commit_paths.append(mv["to"])
            touched.append(mv["to"])
            body = read_text(ctx.abs(mv["to"]))
            if new != old:
                body = re.sub(rf"\bADR-{old:04d}\b", f"ADR-{new:04d}", body)
            atomic_write(ctx.abs(mv["to"]), _add_epic_line(body, mv["epic"]))
            path_re = re.compile(
                rf"[\w./-]*epic-{nnn}/arch/adr-{old:04d}-{re.escape(mv['slug'])}\.md")
            num_re = re.compile(rf"\bADR-{old:04d}\b")
            epic_tree = os.path.join(ctx.impl, f"epic-{nnn}")
            for f in md_files:
                if not os.path.isfile(f):
                    continue
                text = read_text(f)
                inside = _under(f, epic_tree)
                if new != old and not inside:
                    for i, line in enumerate(text.splitlines(), 1):
                        if num_re.search(line):
                            plan["review"].append({"file": ctx.rel(f), "line": i,
                                                   "text": line.strip()})
                text2 = path_re.sub(mv["to"], text)
                if new != old and inside:
                    text2 = num_re.sub(f"ADR-{new:04d}", text2)
                if text2 != text:
                    atomic_write(f, text2)
                    rel = ctx.rel(f)
                    rewritten.add(rel)
                    touched.append(rel)
            if new != old:
                for f in other_docs:
                    if re.match(rf"{old:04d}-", os.path.basename(f)) and _under(f, docs_dir):
                        continue                      # that number's rightful owner
                    for i, line in enumerate(read_text(f).splitlines(), 1):
                        if num_re.search(line):
                            plan["review"].append({"file": ctx.rel(f), "line": i,
                                                   "text": line.strip()})
        rewritten_committed, rewritten_uncommitted = [], []
        for rel in sorted(rewritten):
            if _git(ctx, "ls-files", "--error-unmatch", "--", rel, check=False).returncode == 0:
                commit_paths.append(rel)
                rewritten_committed.append(rel)
            else:
                sys.stderr.write(f"WARN {rel} was rewritten but is not tracked; not committed\n")
                rewritten_uncommitted.append(rel)
        plan["rewritten"] = rewritten_committed
        plan["rewritten_uncommitted"] = rewritten_uncommitted
        plan["commit"] = git_commit(ctx, "docs(adr): migrate epic ADRs to docs/adr",
                                    list(dict.fromkeys(commit_paths)))
    except Exception as e:
        # No automatic rollback: undoing renames and text substitutions across a repo is more
        # dangerous than the problem, and the pre-flight refusal above is what stops a rerun
        # from compounding this. Fail loud instead, naming exactly what this run already
        # touched so a person can inspect and commit or revert those paths by hand. The commit
        # itself is inside this guard too: a commit-time failure (a rejecting hook, or the
        # index lock exhausted after retries) happens once every file is already moved and
        # rewritten -- exactly the state this message exists to describe.
        code = e.code if isinstance(e, SAError) else 2
        detail = ", ".join(dict.fromkeys(touched)) or "(nothing written yet)"
        raise SAError(code, f"{e} -- migrate-adrs --apply failed partway; paths already moved "
                             f"or rewritten in this run: {detail}. Inspect them and either "
                             f"commit or revert exactly those paths by hand -- never a "
                             f"repo-wide discard; other agents share this checkout.") from e
    print(json.dumps(plan, indent=2))
    return 0


# -- CLI -------------------------------------------------------------------------------------- #

def build_parser():
    p = argparse.ArgumentParser(prog="spec-align.py",
                                description="Spec/implementation alignment for l3io-pm.")
    p.add_argument("--project-root", required=True)
    p.add_argument("--planning-root", default="")
    p.add_argument("--impl-root", default="")
    p.add_argument("--state-root", default="", help="default: <impl-root>/state")
    p.add_argument("--pm-status", default="", help="path to pm-status.py")
    p.add_argument("--spec-paths", default=None,
                   help="JSON list of project-relative paths/globs; replaces discovery")
    sub = p.add_subparsers(dest="cmd", required=True)

    b = sub.add_parser("build", help="build the spec index (no LLM)")
    g = b.add_mutually_exclusive_group()
    g.add_argument("--if-stale", action="store_true", help="rewrite only when the specs changed")
    g.add_argument("--check", action="store_true", help="exit 1 when stale; write nothing")
    b.set_defaults(func=cmd_build)

    cp = sub.add_parser("check-pointers", help="provenance: every dimension's Spec: line")
    g = cp.add_mutually_exclusive_group(required=True)
    g.add_argument("--story", nargs="+", help="gate mode: exit 2 on any problem")
    g.add_argument("--all", action="store_true",
                   help="report mode over every story: exit 1 on broken pointers")
    cp.add_argument("--business", choices=("required", "advisory"), default="advisory",
                    help="required: a missing business AC section is an error (gate mode); "
                         "advisory: reported on stderr only")
    cp.set_defaults(func=cmd_check_pointers)

    se = sub.add_parser("sections", help="the stories' pointers as de-duplicated line ranges")
    se.add_argument("--stories", nargs="+", required=True)
    se.set_defaults(func=cmd_sections)

    dp = sub.add_parser("disposition", help="record one drift finding's disposition")
    dp.add_argument("--review", required=True)
    dp.add_argument("--finding", required=True, help="AD-{n} or SD-{nn}-{n}")
    dp.add_argument("--disposition", required=True, choices=list(DISPOSITIONS))
    dp.add_argument("--spec", default="", help="<path>#<anchor> (spec dispositions)")
    dp.add_argument("--adr", default="", help="the ADR (adr-justified; optional otherwise)")
    dp.add_argument("--spec-alignment", default="true", help="pm-execute's spec_alignment")
    dp.set_defaults(func=cmd_disposition)

    cd = sub.add_parser("check-dispositions", help="gate: every BLOCKER/MAJOR disposed")
    cd.add_argument("--review", required=True)
    cd.add_argument("--expect", required=True,
                    help="the reviewer's final 'Blocker: N, Major: N, Minor: N'")
    cd.set_defaults(func=cmd_check_dispositions)

    ad = sub.add_parser("adrs", help="an epic's ADRs, from docs/adr and the old home")
    ad.add_argument("--epic", required=True)
    ad.add_argument("--format", choices=["text", "json"], default="text")
    ad.set_defaults(func=cmd_adrs)

    cl = sub.add_parser("check-links", help="report ADRs their spec section does not link")
    cl.add_argument("--epic", default="")
    cl.set_defaults(func=cmd_check_links)

    le = sub.add_parser("lease", help="the spec-sync lease (acquire | release)")
    lease_sub = le.add_subparsers(dest="lease_cmd", required=True)
    la = lease_sub.add_parser("acquire")
    la.add_argument("--owner", required=True, help="the epic key")
    la.add_argument("--wait-minutes", type=float, default=15.0)
    la.add_argument("--ttl-minutes", type=float, default=30.0)
    la.add_argument("--poll-seconds", type=float, default=5.0)
    lr = lease_sub.add_parser("release")
    lr.add_argument("--owner", required=True)
    le.set_defaults(func=cmd_lease)

    sp = sub.add_parser("sync-plan", help="the epic's pending spec-sync items (JSON)")
    sp.add_argument("--epic", required=True)
    sp.add_argument("--defer", action="store_true",
                    help="write pointer-only proposals + backlog items instead (lease timeout)")
    sp.set_defaults(func=cmd_sync_plan)

    pr = sub.add_parser("propose", help="record an agent-written proposal and its backlog item")
    pr.add_argument("--epic", required=True)
    g = pr.add_mutually_exclusive_group(required=True)
    g.add_argument("--finding", default="")
    g.add_argument("--adr", default="")
    pr.set_defaults(func=cmd_propose)

    co = sub.add_parser("commit", help="guarded docs(spec) commit for one finding or ADR link")
    co.add_argument("--epic", required=True)
    g = co.add_mutually_exclusive_group(required=True)
    g.add_argument("--finding", default="")
    g.add_argument("--adr", default="")
    co.add_argument("--paths", nargs="+", required=True, help="exactly the pointed-to spec file")
    co.add_argument("--rename-anchor", action="append", default=[], metavar="OLD=NEW")
    co.set_defaults(func=cmd_commit)

    rj = sub.add_parser("reject", help="revert/decline a spec item and refile it as a code fix")
    rj.add_argument("--key", required=True)
    rj.set_defaults(func=cmd_reject)

    cs = sub.add_parser("check-stale", help="report unconfirmed spec changes built upon")
    cs.set_defaults(func=cmd_check_stale)

    mi = sub.add_parser("migrate-adrs", help="move ADRs from epic-*/arch/ to docs/adr/")
    g = mi.add_mutually_exclusive_group(required=True)
    g.add_argument("--plan", action="store_true")
    g.add_argument("--apply", action="store_true")
    mi.set_defaults(func=cmd_migrate_adrs)

    # Later tasks register their subcommands above this line.
    return p


def main(argv=None):
    a = build_parser().parse_args(argv)
    try:
        return a.func(Ctx(a), a)
    except SAError as e:
        sys.stderr.write(f"spec-align.py {a.cmd}: {e}\n")
        return e.code


if __name__ == "__main__":
    sys.exit(main())
